form:
    domain: www.msftconnecttest.com
    username: ""
    user_type: cmcc
    password: ""
meta:
    "n": "200"
    type: "1"
    acid: "5"
    enc: srun_bx1
    os: Windows 10
    name: windows
    info_prefix: SRBX1
    double_stack: false
settings:
    basic:
        https: false
        skip_cert_verify: false
        timeout: 5
        interfaces: ""
        interfaces_interval: 0
    guardian:
        enable: false
        duration: 300
    backoff:
        enable: false
        max_retries: 0
        initial_duration: 2
        max_duration: 300
        exponent_factor: 1
        inter_const_factor: 0
        outer_const_factor: 0
    log:
        debug_level: false
        write_file: false
        log_path: ./
        log_name: ""
    ddns:
        enable: false
        ttl: 600
        domain: www.example.com
        provider: cloudflare
        config:
            zone: ""
            token: ""
    reality:
        enable: false
        addr: http://www.baidu.com
    webhook:
        enable: false
        url: ""
        timeout: 30
    custom_header:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
